# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160613_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
