# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20160615_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
    ]
